[workspace]
members = ["packages/*", "packages/*/example"]
resolver = "2"

[workspace.package]
authors = ["Nixy <info@nixy.software>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/NixySoftware/floating-ui"
version = "0.0.1"

[workspace.dependencies]
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
wasm-bindgen = "0.2.92"

[workspace.dependencies.web-sys]
version = "0.3.69"
features = [
    "css",
    "CssStyleDeclaration",
    "Document",
    "DomRect",
    "DomRectList",
    "Element",
    "HtmlElement",
    "HtmlSlotElement",
    "Node",
    "ShadowRoot",
    "Window",
]
