[package]
name = "floating-ui-core"
description = "Positioning library for floating elements: tooltips, popovers, dropdowns, and more."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
floating-ui-utils = { path = "../utils" }
