[package]
name = "floating-ui-leptos"
description = "Floating UI for Leptos."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
floating-ui-core = { path = "../core" }
floating-ui-utils = { path = "../utils" }
leptos = { version = "0.6.9", features = ["nightly"] }
