[package]
name = "floating-ui-leptos"
description = "Floating UI for Leptos."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
cfg-if = "1.0.0"
# TODO: remove
log = "0.4.21"
floating-ui-dom = { path = "../dom", version = "0.0.2" }
leptos = { version = "0.6.9", features = ["nightly"] }
web-sys.workspace = true

[dev-dependencies]
wasm-bindgen-test.workspace = true
