[package]
name = "floating-ui-leptos"
description = "Floating UI for Leptos."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
floating-ui-dom = { path = "../dom", version = "0.0.2" }
leptos = { version = "0.6.9", features = ["nightly"] }
web-sys.workspace = true
