[package]
name = "floating-ui-utils"
description = "Utilities for Floating UI."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
