name: Check for upstream releases

on: [workflow_dispatch]

jobs:
    check:
        name: Check for upstream releases
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Rust toolchain
              run: rustup toolchain install nightly --no-self-update --profile default

            - name: Check for upstream releases
              run: cargo run -p scripts --bin upstream
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GIT_USER_NAME: github-actions[bot]
                  GIT_USER_EMAIL: github-actions[bot]@users.noreply.github.com
                  RUST_LOG: debug
